x = int(input())
y = int(input())
c = input()
f = float(input())
d = float(input())
print(x)
print(y)
print(c)
print('%.2f' % f) # print('{:.2f}.format(f))
print('%.9f' % d) # print('{:.9f}.format(f))