x, y, z, t = map(int, input().split())
print(x, y, z ,t, sep = '  ', end = '\n\n')
print(y, z, x, t, sep = '--', end = '\n\n')
print(2 * x, 3 * y, 4 * z, 5 * t, sep = ',', end = '\n\n')
print('KET THUC !!')